config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users, only: [:new, :create, :show]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :events, except: [:edit, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, :class_name => 'User'
    has_many :event_attendees, :foreign_key => "attended_event_id", :class_name => "EventAttendee"
    has_many :attendees, :through => :event_attendees, source: "attendee" 

    scope :upcoming_events, -> { where("date > ?", Date.current) }
    scope :past_events, -> { where("date < ?", Date.current) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, :class_name => "User"
  belongs_to :attended_event, :class_name => "Event"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :created_events, :foreign_key => "creator_id", :class_name => "Event"
    has_many :event_attendees, :foreign_key => "attendee_id", :class_name => "EventAttendee"
    has_many :attended_events, :through => :event_attendees, source: "attended_event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        @events = Event.all 
        @upcoming = @events.upcoming_events
        @past = @events.past_events
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.created_events.build(event_params)
        if @event.save
            @event.attendees << current_user
            redirect_to current_user
        else 
            render 'new'
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])
        @event.attendees << current_user
        redirect_to events_path
        flash[:success] = "You've joined the event!"
    end

    private

    def event_params
        params.require(:event).permit(:description, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(name: params[:session][:name])
        if user
            log_in user
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        session.delete(:user_id)
        @current_user = nil
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user 
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = upcoming_events(@user)
    @prev_events = previous_events(@user)
  end


  

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
  def upcoming_events(user)
    user.attended_events.where("date > ?", Date.current)
  end

  def previous_events(user)
    user.attended_events.where("date < ?", Date.current)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id 
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>
<h3>Upcoming Events</h3>
<ul>
  <% @upcoming.each do |e| %>
    <li>
        <%= link_to e.description, event_path(e) %>
        Created by: <%= link_to e.creator.name, user_path(e.creator) %>
    </li>
  <% end %>
</ul>

<h3>Past Events</h3>
<ul>
  <% @past.each do |e| %>
    <li>
        <%= link_to e.description, event_path(e) %>
        Created by: <%= link_to e.creator.name, user_path(e.creator) %>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>Create an event</h1>

<%= form_for @event do |f| %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :date %>
    <%= f.date_field :date %>

    <%= f.submit "Submit" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.description %></h1>
<h1>On: <%= @event.date %></h1>
<h3>Created by: <%= @event.creator.name %></h3>
<h4><%= link_to "Join", event_path(@event), method: :patch %></h4>
<p>Attendees: </p>
<ul>
<% @event.attendees.each do |n| %>
    <li>
      <%= n.name %>
    </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user.nil? %>
      <%= link_to @current_user.name, user_path(@current_user)  %>
      <%= link_to "Log out", logout_path, method: :delete %>
      <%= link_to "Create Event", new_event_path %>
      <%= link_to "See All Events", events_path %>
    <% end %>
    <% flash.each do |message_type, message| %>
      <h1><%= message %></h1>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<h1>Hi, <%= @user.name %></h1>

<h3>Upcoming Events</h3>

<ul>
  <% @upcoming_events.each do |u| %>
    <li>
      <%= u.description %>
    </li>
  <% end %>
</ul>

<h3>Previous Events</h3>

<ul>
  <% @prev_events.each do |p| %>
    <li>
      <%= p.description %>
    </li>
  <% end %>
</ul>